import type { Customer, BrandId } from "@/lib/types";

/**
 * BIN ESSA GROUP — Official Wholesale Client Accounts & Retail Partners
 * Key supermarket chains, convenience stores, and vape shop network across Kuwait.
 */
export interface B2BCustomer extends Customer {
  brandId: BrandId;
  code?: string;
  phone?: string;
  email?: string;
  address?: string;
}

export const customers: B2BCustomer[] = [
  {
    id: "cust-001",
    code: "CUST-TRL-01",
    nameEn: "Trolley Convenience Stores",
    nameAr: "سلسلة أسواق ترولي المركزية",
    customerType: "wholesale",
    balanceKd: 4250.0,
    creditLimitKd: 15000.0,
    brandId: "smoking",
    phone: "+965 2200 1111",
    email: "procurement@trolley.com.kw",
    address: "Al-Rai Industrial Area, Block 1",
  },
  {
    id: "cust-002",
    code: "CUST-BDG-02",
    nameEn: "Bodega Kuwait Chain",
    nameAr: "سلسلة بوديجا كويت",
    customerType: "wholesale",
    balanceKd: 1850.5,
    creditLimitKd: 8000.0,
    brandId: "smoking",
    phone: "+965 2200 2222",
    email: "purchasing@bodegakw.com",
    address: "Shuwaikh Industrial Area 2",
  },
  {
    id: "cust-003",
    code: "CUST-LUL-03",
    nameEn: "Lulu Hypermarket Kuwait",
    nameAr: "شركة لولو هايبرماركت الكويت",
    customerType: "wholesale",
    balanceKd: 6800.0,
    creditLimitKd: 25000.0,
    brandId: "smoking",
    phone: "+965 2200 3333",
    email: "tobacco.buyer@luluhypermarket.com",
    address: "Al-Rai, 4th Ring Road",
  },
  {
    id: "cust-004",
    code: "CUST-HNB-04",
    nameEn: "Hi & Buy Supermarkets",
    nameAr: "أسواق هاي آند باي المركزية",
    customerType: "wholesale",
    balanceKd: 920.0,
    creditLimitKd: 5000.0,
    brandId: "smoking",
    phone: "+965 2200 4444",
    email: "orders@hiandbuy.kw",
    address: "Hawally, Tunis Street",
  },
  {
    id: "cust-005",
    code: "CUST-NAS-05",
    nameEn: "Al Naser Trading & Retail Co.",
    nameAr: "شركة النصر الرياضي والتجاري",
    customerType: "wholesale",
    balanceKd: 2400.0,
    creditLimitKd: 10000.0,
    brandId: "smoking",
    phone: "+965 2200 5555",
    email: "corporate@alnaser.com.kw",
    address: "Farwaniya Commercial Zone",
  },
  {
    id: "cust-006",
    code: "CUST-ONC-06",
    nameEn: "Oncost Cash & Carry",
    nameAr: "أسواق أون كوست المركزية",
    customerType: "wholesale",
    balanceKd: 5120.0,
    creditLimitKd: 20000.0,
    brandId: "smoking",
    phone: "+965 2200 6666",
    email: "supply@oncost.com.kw",
    address: "Sulaibiya Central Market",
  },
  {
    id: "cust-007",
    code: "CUST-DUK-07",
    nameEn: "Dukan Hypermarkets",
    nameAr: "أسواق دكان الكويت",
    customerType: "wholesale",
    balanceKd: 1450.0,
    creditLimitKd: 7500.0,
    brandId: "smoking",
    phone: "+965 2200 7777",
    email: "buying@dukan.kw",
    address: "Mahboula Coastal Road",
  },
  {
    id: "cust-008",
    code: "CUST-CTC-08",
    nameEn: "City Centre Kuwait",
    nameAr: "سيتي سنتر هايبرماركت",
    customerType: "wholesale",
    balanceKd: 3890.0,
    creditLimitKd: 15000.0,
    brandId: "smoking",
    phone: "+965 2200 8888",
    email: "procurement@citycentre.com.kw",
    address: "Salmiya, Salem Al-Mubarak St.",
  },
  {
    id: "cust-009",
    code: "CUST-VPG-09",
    nameEn: "The Vape Gate Kuwait (Vape Shop Network)",
    nameAr: "شبكة محلات ذا فيب جيت الكويت",
    customerType: "b2b_portal",
    balanceKd: 1100.0,
    creditLimitKd: 6000.0,
    brandId: "smoking",
    phone: "+965 9000 1234",
    email: "vapegate.orders@gmail.com",
    address: "Salmiya Commercial Complex",
  },
  {
    id: "cust-010",
    code: "CUST-ACL-10",
    nameEn: "A-Class Grocery & Mini Markets Group",
    nameAr: "مجموعة بقالات وأسواق الفئة الأولى (A-Class)",
    customerType: "wholesale",
    balanceKd: 840.0,
    creditLimitKd: 4000.0,
    brandId: "smoking",
    phone: "+965 9988 7766",
    email: "aclass.retail@kw.com",
    address: "Various branches across Kuwait",
  },
  {
    id: "cust-011",
    code: "CUST-MAR-11",
    nameEn: "Marina Gear & Fishing Center Khiran",
    nameAr: "مركز مارينا جير لمعدات الصيد - الخيران",
    customerType: "b2b_portal",
    balanceKd: 450.0,
    creditLimitKd: 3000.0,
    brandId: "khiran",
    phone: "+965 6655 4433",
    email: "marinagear.khiran@gmail.com",
    address: "Khiran Marina Resort, Block 3",
  },
  {
    id: "cust-012",
    code: "CUST-ART-12",
    nameEn: "Gulf Creative Gifts & Advertising LLC",
    nameAr: "شركة خليج الإبداع للهدايا والإعلان",
    customerType: "b2b_portal",
    balanceKd: 280.0,
    creditLimitKd: 2500.0,
    brandId: "jmart",
    phone: "+965 5544 3322",
    email: "creative.gifts@gulfmedia.kw",
    address: "Sharq Commercial Tower",
  },
];
