import type { Item } from "@/lib/types";

/**
 * BIN ESSA SMOKING CENTER (Est. 2010) — Official Enterprise Catalog
 * Real Product Portfolio covering Bin Essa's 12 Smoking branches,
 * Bin Essa Khiran (Marine & Outdoor), and JM Art Zone (Gifts & Signage).
 */
export const items: Item[] = [
  // 1. Disposable Vape Devices (Beco, Wafer, BLVK, Click, AL BASHA)
  {
    id: "item-001",
    sku: "VP-BECO-PRO-6K",
    barcode: "6281234500019",
    nameEn: "Beco Pro 6000 Puffs - Tropical Mix",
    nameAr: "بيكو برو 6000 سحبة - تروبيكال مكس",
    category: "disposable_vapes",
    brandId: "smoking",
    costPriceKd: 2.800,
    sellPriceKd: 5.500,
    wholesalePriceKd: 4.200,
    stockByBranch: { "br-01": 85, "br-02": 40, "br-03": 55, "br-08": 400 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-002",
    sku: "VP-WAF-DISP-5K",
    barcode: "6281234500026",
    nameEn: "Wafer 5000 Puffs - Blueberry Ice",
    nameAr: "ويفر 5000 سحبة - توت أزرق بارد",
    category: "disposable_vapes",
    brandId: "smoking",
    costPriceKd: 2.400,
    sellPriceKd: 4.750,
    wholesalePriceKd: 3.800,
    stockByBranch: { "br-01": 60, "br-02": 25, "br-04": 30, "br-08": 250 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-003",
    sku: "VP-BLVK-ELQ-30M",
    barcode: "6281234500033",
    nameEn: "BLVK Unicorn Salt - Cuban Cigar 30ML (35mg)",
    nameAr: "نكهة بي إل في كي يونيكورن سولت - سيجار كوبي 30 مل",
    category: "pod_systems",
    brandId: "smoking",
    costPriceKd: 2.200,
    sellPriceKd: 4.500,
    wholesalePriceKd: 3.400,
    stockByBranch: { "br-01": 45, "br-03": 20, "br-08": 180 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-004",
    sku: "VP-CLK-DISP-7K",
    barcode: "6281234500040",
    nameEn: "Click 7000 Puffs - Double Apple Ice",
    nameAr: "كليك 7000 سحبة - تفاحتين مثلج",
    category: "disposable_vapes",
    brandId: "smoking",
    costPriceKd: 3.000,
    sellPriceKd: 6.000,
    wholesalePriceKd: 4.600,
    stockByBranch: { "br-01": 90, "br-02": 35, "br-06": 40, "br-08": 500 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-005",
    sku: "VP-BASHA-POD-01",
    barcode: "6281234500057",
    nameEn: "AL BASHA Pod Device Kit 1000mAh",
    nameAr: "جهاز الباشا بود سيستم 1000 مل أمبير",
    category: "pod_systems",
    brandId: "smoking",
    costPriceKd: 4.500,
    sellPriceKd: 8.500,
    wholesalePriceKd: 6.500,
    stockByBranch: { "br-01": 35, "br-02": 15, "br-08": 120 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 2. Nicotine Pouches (Fox, SIBERIA, Bagz, Velo)
  {
    id: "item-006",
    sku: "NP-FOX-WHT-16G",
    barcode: "6281234500064",
    nameEn: "White Fox All White Portion Nicotine Pouches (16mg)",
    nameAr: "أكياس وايت فوكس نيكوتين أول وايت (16 ملغ)",
    category: "nicotine_pouches",
    brandId: "smoking",
    costPriceKd: 0.950,
    sellPriceKd: 1.750,
    wholesalePriceKd: 1.350,
    stockByBranch: { "br-01": 150, "br-02": 45, "br-03": 80, "br-08": 600 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-007",
    sku: "NP-SIB-RED-13G",
    barcode: "6281234500071",
    nameEn: "SIBERIA -80°C Extremely Strong Nicotine Pouches (Red)",
    nameAr: "سيبيريا -80 إكستريم سترونغ أكياس نيكوتين (أحمر)",
    category: "nicotine_pouches",
    brandId: "smoking",
    costPriceKd: 1.100,
    sellPriceKd: 2.000,
    wholesalePriceKd: 1.500,
    stockByBranch: { "br-01": 110, "br-04": 30, "br-08": 450 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-008",
    sku: "NP-BAGZ-FRT-08G",
    barcode: "6281234500088",
    nameEn: "Bagz Nicotine Pouches - Arctic Freeze (12mg)",
    nameAr: "باجز أكياس نيكوتين - أركتيك فريز (12 ملغ)",
    category: "nicotine_pouches",
    brandId: "smoking",
    costPriceKd: 0.850,
    sellPriceKd: 1.500,
    wholesalePriceKd: 1.200,
    stockByBranch: { "br-01": 70, "br-02": 25, "br-08": 300 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 3. Cigarette Lighters (Cricket, Fuego, Clipper)
  {
    id: "item-009",
    sku: "LT-CRK-ORIG-01",
    barcode: "6281234500095",
    nameEn: "Cricket Original Disposable Lighter - Pack of 50",
    nameAr: "ولاعة كريكيت أصلية - بوكس 50 حبة",
    category: "cigarette_lighters",
    brandId: "smoking",
    costPriceKd: 4.500,
    sellPriceKd: 7.500,
    wholesalePriceKd: 5.800,
    stockByBranch: { "br-01": 40, "br-03": 15, "br-08": 200 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-010",
    sku: "LT-FUE-TURB-01",
    barcode: "6281234500101",
    nameEn: "Fuego Windproof Turbo Jet Torch Lighter",
    nameAr: "ولاعة فويغو توربو جيت مقاومة للرياح",
    category: "cigarette_lighters",
    brandId: "smoking",
    costPriceKd: 0.750,
    sellPriceKd: 1.500,
    wholesalePriceKd: 1.100,
    stockByBranch: { "br-01": 95, "br-02": 30, "br-08": 350 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 4. Rolling Papers & Cones (RAW, Cones, Laze)
  {
    id: "item-011",
    sku: "RP-RAW-KS-SLM",
    barcode: "6281234500118",
    nameEn: "RAW Classic King Size Slim Rolling Papers (Box of 50)",
    nameAr: "ورق لف راو كلاسيك كينغ سايز سليم (علبة 50)",
    category: "rolling_papers",
    brandId: "smoking",
    costPriceKd: 6.500,
    sellPriceKd: 12.000,
    wholesalePriceKd: 9.000,
    stockByBranch: { "br-01": 50, "br-02": 20, "br-08": 220 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-012",
    sku: "RP-CON-PRE-3PK",
    barcode: "6281234500125",
    nameEn: "Cones Pre-Rolled King Size (Pack of 32 Cones)",
    nameAr: "مخاريط جاهزة كونز كينغ سايز (عبوة 32 حبة)",
    category: "rolling_papers",
    brandId: "smoking",
    costPriceKd: 1.200,
    sellPriceKd: 2.250,
    wholesalePriceKd: 1.700,
    stockByBranch: { "br-01": 80, "br-03": 25, "br-08": 320 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-013",
    sku: "RP-LAZ-ORG-SLM",
    barcode: "6281234500132",
    nameEn: "Laze Organic Hemp Slim Rolling Papers + Tips",
    nameAr: "ورق لف ليز قنب عضوي سليم مع فلاتر",
    category: "rolling_papers",
    brandId: "smoking",
    costPriceKd: 0.350,
    sellPriceKd: 0.750,
    wholesalePriceKd: 0.550,
    stockByBranch: { "br-01": 130, "br-02": 40, "br-08": 600 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 5. Charcoal & Shisha Accessories (CHARCOAL CROWN 40 MM)
  {
    id: "item-014",
    sku: "CH-CRW-40M-BOX",
    barcode: "6281234500149",
    nameEn: "CHARCOAL CROWN 40 MM Quick-Light Coal (Box of 100)",
    nameAr: "فحم كراون سريع الاشتعال 40 ملم (علبة 100 قرص)",
    category: "general_smoking_accessories",
    brandId: "smoking",
    costPriceKd: 1.600,
    sellPriceKd: 3.000,
    wholesalePriceKd: 2.250,
    stockByBranch: { "br-01": 75, "br-03": 30, "br-08": 450 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 6. Dokha & Medwakh (Al Basha & Premium Medwakh)
  {
    id: "item-015",
    sku: "DK-BAS-MED-01B",
    barcode: "6281234500156",
    nameEn: "Al Basha Special Dokha Warm (Medium Blend 50ml)",
    nameAr: "دوخة الباشا الخاصة دافئة (خلطة متوسطة 50 مل)",
    category: "dokha_medwakh",
    brandId: "smoking",
    costPriceKd: 1.800,
    sellPriceKd: 3.500,
    wholesalePriceKd: 2.600,
    stockByBranch: { "br-01": 65, "br-02": 25, "br-08": 300 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-016",
    sku: "DK-MDW-WD-GOLD",
    barcode: "6281234500163",
    nameEn: "Handcrafted Ebony Wood Medwakh with Gold Ring",
    nameAr: "مدواخ خشب أبنوس يدوي الصنع مع حلقة ذهبية",
    category: "dokha_medwakh",
    brandId: "smoking",
    costPriceKd: 3.200,
    sellPriceKd: 6.500,
    wholesalePriceKd: 4.800,
    stockByBranch: { "br-01": 40, "br-04": 15, "br-08": 150 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 7. Rolling Paper Tobacco (HBT) & Pipe Accessories
  {
    id: "item-017",
    sku: "TB-GLD-VIR-50G",
    barcode: "6281234500170",
    nameEn: "Golden Virginia Rolling Tobacco Pouch (50g)",
    nameAr: "تبغ لف غولدن فيرجينيا أوريجينال (50 غرام)",
    category: "rolling_tobacco_hbt",
    brandId: "smoking",
    costPriceKd: 2.100,
    sellPriceKd: 3.750,
    wholesalePriceKd: 2.950,
    stockByBranch: { "br-01": 55, "br-03": 20, "br-08": 280 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-018",
    sku: "PA-BR-PIPE-9MM",
    barcode: "6281234500187",
    nameEn: "Classic Briar Wood Smoking Pipe (9mm Filter)",
    nameAr: "غليون كلاسيكي خشب براير (فلتر 9 ملم)",
    category: "pipe_accessories",
    brandId: "smoking",
    costPriceKd: 4.200,
    sellPriceKd: 8.500,
    wholesalePriceKd: 6.200,
    stockByBranch: { "br-01": 25, "br-02": 10, "br-08": 90 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["smoking"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 8. Bin Essa Khiran (Marine & Outdoor)
  {
    id: "item-019",
    sku: "MR-DAI-ROD-CB1",
    barcode: "6281234500194",
    nameEn: "Daiwa Saltist Boat Fishing Rod Combo 7ft",
    nameAr: "قصبة صيد دايوا سالتيست للبحر والقوارب 7 قدم",
    category: "marine_outdoor",
    brandId: "khiran",
    costPriceKd: 18.000,
    sellPriceKd: 32.500,
    wholesalePriceKd: 24.000,
    stockByBranch: { "br-15": 18, "br-08": 50 },
    hasVariants: false,
    hasSerials: true,
    visibility: { mode: "inherit", companies: ["khiran"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-020",
    sku: "MR-SHM-REL-400",
    barcode: "6281234500200",
    nameEn: "Shimano Sedona 4000 Spinning Reel",
    nameAr: "ماكينة صيد شيمانو سيدونا 4000 سبينينغ",
    category: "marine_outdoor",
    brandId: "khiran",
    costPriceKd: 14.500,
    sellPriceKd: 26.000,
    wholesalePriceKd: 19.500,
    stockByBranch: { "br-15": 22, "br-08": 60 },
    hasVariants: false,
    hasSerials: true,
    visibility: { mode: "inherit", companies: ["khiran"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },

  // 9. JM Art Zone (Customized Gifts, Acrylics, Mugs & Signage)
  {
    id: "item-021",
    sku: "JM-ACR-DESK-SN",
    barcode: "6281234500217",
    nameEn: "Custom Laser Cut Acrylic Executive Desk Sign",
    nameAr: "لافتة مكتبية تنفيذية أكريليك مخصصة قص ليزر",
    category: "custom_gifts_signage",
    brandId: "jmart",
    costPriceKd: 3.500,
    sellPriceKd: 9.500,
    wholesalePriceKd: 6.500,
    stockByBranch: { "br-16": 30, "br-17": 25, "br-08": 150 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["jmart"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
  {
    id: "item-022",
    sku: "JM-PRN-MUG-CST",
    barcode: "6281234500224",
    nameEn: "Personalized Ceramic Sublimation Coffee Mug",
    nameAr: "كوب قهوة سيراميك طباعة حرارية مخصصة",
    category: "custom_gifts_signage",
    brandId: "jmart",
    costPriceKd: 0.650,
    sellPriceKd: 2.500,
    wholesalePriceKd: 1.500,
    stockByBranch: { "br-16": 80, "br-17": 60, "br-08": 400 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: ["jmart"] },
    blockDiscount: false,
    blockFreeGift: false,
    blockSale: false,
  },
];
