import type { Item } from "@/lib/types";

// Sample catalog for POS/Inventory screens. Real catalog is 20,000+ SKUs;
// this is a realistic slice covering each category and brand for Stage 1.

export const items: Item[] = [
  {
    id: "item-001",
    sku: "VP-IQ-TRY-001",
    barcode: "6281234500019",
    nameEn: "IQOS Terea Yellow (Pack of 20)",
    nameAr: "آيكوس تيريا أصفر (علبة 20)",
    // TEMP: category placeholder until client confirms where IQOS/heated-tobacco
    // sticks belong (Rolling Paper Tobacco (HBT) vs General Smoking Accessories).
    category: "general_smoking_accessories",
    brandId: "smoking",
    costPriceKd: 1.450,
    sellPriceKd: 2.250,
    wholesalePriceKd: 1.950,
    stockByBranch: { "br-01": 42, "br-02": 8, "br-03": 30, "br-06": 15 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-002",
    sku: "NP-VEL-MNT-001",
    barcode: "6281234500026",
    nameEn: "Velo Nicotine Pouches - Mint (Can)",
    nameAr: "فيلو أكياس نيكوتين - نعناع (علبة)",
    category: "nicotine_pouches",
    brandId: "smoking",
    costPriceKd: 0.850,
    sellPriceKd: 1.500,
    wholesalePriceKd: 1.250,
    stockByBranch: { "br-01": 60, "br-02": 5, "br-04": 22 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-003",
    sku: "AC-CLP-LTR-001",
    barcode: "6281234500033",
    nameEn: "Clipper Lighter - Assorted Colors",
    nameAr: "ولاعة كليبر - ألوان متنوعة",
    category: "cigarette_lighters",
    brandId: "smoking",
    costPriceKd: 0.250,
    sellPriceKd: 0.500,
    wholesalePriceKd: 0.400,
    stockByBranch: { "br-01": 120, "br-03": 12, "br-08": 300 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-004",
    sku: "VP-ELF-BAR-001",
    barcode: "6281234500040",
    nameEn: "Elf Bar Disposable Vape - Blue Razz",
    nameAr: "إلف بار فيب للاستعمال مرة واحدة - بلو راز",
    category: "disposable_vapes",
    brandId: "smoking",
    costPriceKd: 1.200,
    sellPriceKd: 2.000,
    wholesalePriceKd: 1.700,
    stockByBranch: { "br-01": 35, "br-05": 18, "br-09": 27 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-005",
    sku: "AC-ASH-STL-001",
    barcode: "6281234500057",
    nameEn: "Stainless Steel Ashtray - Windproof",
    nameAr: "منفضة سجائر ستانلس ستيل - مقاومة للرياح",
    category: "general_smoking_accessories",
    brandId: "smoking",
    costPriceKd: 1.800,
    sellPriceKd: 3.250,
    wholesalePriceKd: 2.750,
    stockByBranch: { "br-01": 20, "br-13": 14 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-006",
    sku: "MO-LFJ-VST-001",
    barcode: "6281234500064",
    nameEn: "Life Jacket - Adult (Coast Guard Approved)",
    nameAr: "سترة نجاة - للبالغين (معتمدة من خفر السواحل)",
    category: "marine_outdoor",
    brandId: "khiran",
    costPriceKd: 8.500,
    sellPriceKd: 15.000,
    wholesalePriceKd: 12.500,
    stockByBranch: { "br-15": 40 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-007",
    sku: "MO-FSH-ROD-001",
    barcode: "6281234500071",
    nameEn: "Fishing Rod - Carbon Fiber 2.4m",
    nameAr: "سنارة صيد - ألياف كربون 2.4 متر",
    category: "marine_outdoor",
    brandId: "khiran",
    costPriceKd: 12.000,
    sellPriceKd: 22.500,
    wholesalePriceKd: 19.000,
    stockByBranch: { "br-15": 25 },
    hasVariants: false,
    hasSerials: true,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-008",
    sku: "MO-ICE-BOX-001",
    barcode: "6281234500088",
    nameEn: "Cooler Box - 45L Marine Grade",
    nameAr: "صندوق تبريد - 45 لتر درجة بحرية",
    category: "marine_outdoor",
    brandId: "khiran",
    costPriceKd: 15.000,
    sellPriceKd: 28.000,
    wholesalePriceKd: 24.000,
    stockByBranch: { "br-15": 18 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-009",
    sku: "GF-MUG-CUS-001",
    barcode: "6281234500095",
    nameEn: "Custom Printed Mug - Personalized Photo",
    nameAr: "كوب مطبوع مخصص - صورة شخصية",
    category: "custom_gifts_signage",
    brandId: "jmart",
    costPriceKd: 1.200,
    sellPriceKd: 3.000,
    wholesalePriceKd: 2.500,
    stockByBranch: { "br-16": 80, "br-17": 45 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-010",
    sku: "GF-SGN-ACR-001",
    barcode: "6281234500101",
    nameEn: "Acrylic Name Sign - Custom Engraved",
    nameAr: "لافتة أكريليك بالاسم - حفر مخصص",
    category: "custom_gifts_signage",
    brandId: "jmart",
    costPriceKd: 2.500,
    sellPriceKd: 6.000,
    wholesalePriceKd: 5.000,
    stockByBranch: { "br-16": 30, "br-17": 22 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-011",
    sku: "GF-FRM-PHT-001",
    barcode: "6281234500118",
    nameEn: "Custom Photo Frame - Wooden A4",
    nameAr: "برواز صور مخصص - خشبي A4",
    category: "custom_gifts_signage",
    brandId: "jmart",
    costPriceKd: 1.800,
    sellPriceKd: 4.500,
    wholesalePriceKd: 3.750,
    stockByBranch: { "br-16": 25, "br-17": 12 },
    hasVariants: false,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
  {
    id: "item-012",
    sku: "VP-JUL-POD-001",
    barcode: "6281234500125",
    nameEn: "Juul Pod Device - Starter Kit",
    nameAr: "جهاز جول بود - طقم البداية",
    category: "pod_systems",
    brandId: "smoking",
    costPriceKd: 4.500,
    sellPriceKd: 8.000,
    wholesalePriceKd: 6.750,
    stockByBranch: { "br-01": 15, "br-02": 6, "br-10": 9 },
    hasVariants: true,
    hasSerials: false,
    visibility: { mode: "inherit", companies: [] },
  },
];
