import { PrismaClient, ItemCategory } from '../generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';

dotenv.config();

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

interface MasterItemSeed {
  id: string;
  sku: string;
  barcode: string;
  name: string;
  nameEn: string;
  nameAr: string;
  category: ItemCategory;
  subCategory: string;
  brand: string;
  countryOfOrigin: string;
  cost: number;
  price: number;
  retailPrice: number;
  semiWholesalePrice: number;
  wholesalePrice: number;
  unit: string;
  stockQuantity: number;
  isActive: boolean;
  allowSale: boolean;
  allowPurchase: boolean;
  allowDiscount: boolean;
  allowGift: boolean;
  posVisibility: boolean;
}

const officialItems: MasterItemSeed[] = [
  {
    id: "item-001",
    sku: "VP-BECO-PRO-6K",
    barcode: "6281234500019",
    name: "Beco Pro 6000 Puffs - Tropical Mix",
    nameEn: "Beco Pro 6000 Puffs - Tropical Mix",
    nameAr: "بيكو برو 6000 سحبة - تروبيكال مكس",
    category: ItemCategory.ELECTRONICS,
    subCategory: "6000 Puffs",
    brand: "Beco",
    countryOfOrigin: "China",
    cost: 2.800,
    price: 5.500,
    retailPrice: 5.500,
    semiWholesalePrice: 4.800,
    wholesalePrice: 4.200,
    unit: "pcs",
    stockQuantity: 580,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-002",
    sku: "VP-WAF-DISP-5K",
    barcode: "6281234500026",
    name: "Wafer 5000 Puffs - Blueberry Ice",
    nameEn: "Wafer 5000 Puffs - Blueberry Ice",
    nameAr: "ويفر 5000 سحبة - توت أزرق بارد",
    category: ItemCategory.ELECTRONICS,
    subCategory: "5000 Puffs",
    brand: "Wafer",
    countryOfOrigin: "China",
    cost: 2.400,
    price: 4.750,
    retailPrice: 4.750,
    semiWholesalePrice: 4.200,
    wholesalePrice: 3.800,
    unit: "pcs",
    stockQuantity: 365,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-003",
    sku: "VP-BLVK-ELQ-30M",
    barcode: "6281234500033",
    name: "BLVK Unicorn Salt - Cuban Cigar 30ML (35mg)",
    nameEn: "BLVK Unicorn Salt - Cuban Cigar 30ML (35mg)",
    nameAr: "نكهة بي إل في كي يونيكورن سولت - سيجار كوبي 30 مل",
    category: ItemCategory.TOBACCO,
    subCategory: "Nic Salt E-Liquid",
    brand: "BLVK Unicorn",
    countryOfOrigin: "USA",
    cost: 2.200,
    price: 4.500,
    retailPrice: 4.500,
    semiWholesalePrice: 3.900,
    wholesalePrice: 3.400,
    unit: "bottle",
    stockQuantity: 245,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-004",
    sku: "VP-CLK-DISP-7K",
    barcode: "6281234500040",
    name: "Click 7000 Puffs - Double Apple Ice",
    nameEn: "Click 7000 Puffs - Double Apple Ice",
    nameAr: "كليك 7000 سحبة - تفاحتين مثلج",
    category: ItemCategory.ELECTRONICS,
    subCategory: "7000 Puffs",
    brand: "Click",
    countryOfOrigin: "China",
    cost: 3.000,
    price: 6.000,
    retailPrice: 6.000,
    semiWholesalePrice: 5.200,
    wholesalePrice: 4.600,
    unit: "pcs",
    stockQuantity: 665,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-005",
    sku: "VP-BASHA-POD-01",
    barcode: "6281234500057",
    name: "AL BASHA Pod Device Kit 1000mAh",
    nameEn: "AL BASHA Pod Device Kit 1000mAh",
    nameAr: "جهاز الباشا بود سيستم 1000 مل أمبير",
    category: ItemCategory.ELECTRONICS,
    subCategory: "Pod Kits",
    brand: "AL BASHA",
    countryOfOrigin: "UAE",
    cost: 4.500,
    price: 8.500,
    retailPrice: 8.500,
    semiWholesalePrice: 7.200,
    wholesalePrice: 6.500,
    unit: "kit",
    stockQuantity: 170,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-006",
    sku: "NP-FOX-WHT-16G",
    barcode: "6281234500064",
    name: "White Fox All White Portion Nicotine Pouches (16mg)",
    nameEn: "White Fox All White Portion Nicotine Pouches (16mg)",
    nameAr: "أكياس وايت فوكس نيكوتين أول وايت (16 ملغ)",
    category: ItemCategory.TOBACCO,
    subCategory: "All White",
    brand: "White Fox",
    countryOfOrigin: "Sweden",
    cost: 0.950,
    price: 1.750,
    retailPrice: 1.750,
    semiWholesalePrice: 1.500,
    wholesalePrice: 1.350,
    unit: "tin",
    stockQuantity: 875,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-007",
    sku: "NP-SIB-RED-13G",
    barcode: "6281234500071",
    name: "SIBERIA -80°C Extremely Strong Nicotine Pouches (Red)",
    nameEn: "SIBERIA -80°C Extremely Strong Nicotine Pouches (Red)",
    nameAr: "سيبيريا -80 إكستريم سترونغ أكياس نيكوتين (أحمر)",
    category: ItemCategory.TOBACCO,
    subCategory: "Strong Portion",
    brand: "SIBERIA",
    countryOfOrigin: "Sweden",
    cost: 1.100,
    price: 2.000,
    retailPrice: 2.000,
    semiWholesalePrice: 1.700,
    wholesalePrice: 1.500,
    unit: "tin",
    stockQuantity: 590,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-008",
    sku: "NP-BAGZ-FRT-08G",
    barcode: "6281234500088",
    name: "Bagz Nicotine Pouches - Arctic Freeze (12mg)",
    nameEn: "Bagz Nicotine Pouches - Arctic Freeze (12mg)",
    nameAr: "باجز أكياس نيكوتين - أركتيك فريز (12 ملغ)",
    category: ItemCategory.TOBACCO,
    subCategory: "Fruit & Mint",
    brand: "Bagz",
    countryOfOrigin: "Poland",
    cost: 0.850,
    price: 1.500,
    retailPrice: 1.500,
    semiWholesalePrice: 1.300,
    wholesalePrice: 1.200,
    unit: "tin",
    stockQuantity: 395,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-009",
    sku: "LT-CRK-ORIG-01",
    barcode: "6281234500095",
    name: "Cricket Original Disposable Lighter - Pack of 50",
    nameEn: "Cricket Original Disposable Lighter - Pack of 50",
    nameAr: "ولاعة كريكيت أصلية - بوكس 50 حبة",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Flint Lighters",
    brand: "Cricket",
    countryOfOrigin: "Netherlands",
    cost: 4.500,
    price: 7.500,
    retailPrice: 7.500,
    semiWholesalePrice: 6.500,
    wholesalePrice: 5.800,
    unit: "box",
    stockQuantity: 255,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-010",
    sku: "LT-FUE-TURB-01",
    barcode: "6281234500101",
    name: "Fuego Windproof Turbo Jet Torch Lighter",
    nameEn: "Fuego Windproof Turbo Jet Torch Lighter",
    nameAr: "ولاعة فويغو توربو جيت مقاومة للرياح",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Jet Torch",
    brand: "Fuego",
    countryOfOrigin: "Germany",
    cost: 0.750,
    price: 1.500,
    retailPrice: 1.500,
    semiWholesalePrice: 1.250,
    wholesalePrice: 1.100,
    unit: "pcs",
    stockQuantity: 475,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-011",
    sku: "RP-RAW-KS-SLM",
    barcode: "6281234500118",
    name: "RAW Classic King Size Slim Rolling Papers (Box of 50)",
    nameEn: "RAW Classic King Size Slim Rolling Papers (Box of 50)",
    nameAr: "ورق لف راو كلاسيك كينغ سايز سليم (علبة 50)",
    category: ItemCategory.ACCESSORIES,
    subCategory: "King Size Slim",
    brand: "RAW",
    countryOfOrigin: "Spain",
    cost: 6.500,
    price: 12.000,
    retailPrice: 12.000,
    semiWholesalePrice: 10.000,
    wholesalePrice: 9.000,
    unit: "box",
    stockQuantity: 290,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-012",
    sku: "RP-CON-PRE-3PK",
    barcode: "6281234500125",
    name: "Cones Pre-Rolled King Size (Pack of 32 Cones)",
    nameEn: "Cones Pre-Rolled King Size (Pack of 32 Cones)",
    nameAr: "مخاريط جاهزة كونز كينغ سايز (عبوة 32 حبة)",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Pre-Rolled Cones",
    brand: "Cones",
    countryOfOrigin: "Netherlands",
    cost: 1.200,
    price: 2.250,
    retailPrice: 2.250,
    semiWholesalePrice: 1.900,
    wholesalePrice: 1.700,
    unit: "pack",
    stockQuantity: 425,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-013",
    sku: "RP-LAZ-ORG-SLM",
    barcode: "6281234500132",
    name: "Laze Organic Hemp Slim Rolling Papers + Tips",
    nameEn: "Laze Organic Hemp Slim Rolling Papers + Tips",
    nameAr: "ورق لف ليز قنب عضوي سليم مع فلاتر",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Organic Hemp",
    brand: "Laze",
    countryOfOrigin: "France",
    cost: 0.350,
    price: 0.750,
    retailPrice: 0.750,
    semiWholesalePrice: 0.600,
    wholesalePrice: 0.550,
    unit: "booklet",
    stockQuantity: 770,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-014",
    sku: "CH-CRW-40M-BOX",
    barcode: "6281234500149",
    name: "CHARCOAL CROWN 40 MM Quick-Light Coal (Box of 100)",
    nameEn: "CHARCOAL CROWN 40 MM Quick-Light Coal (Box of 100)",
    nameAr: "فحم كراون سريع الاشتعال 40 ملم (علبة 100 قرص)",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Quick-Light Charcoal",
    brand: "Crown",
    countryOfOrigin: "Holland",
    cost: 1.600,
    price: 3.000,
    retailPrice: 3.000,
    semiWholesalePrice: 2.500,
    wholesalePrice: 2.250,
    unit: "box",
    stockQuantity: 555,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-015",
    sku: "DK-BAS-MED-01B",
    barcode: "6281234500156",
    name: "Al Basha Special Dokha Warm (Medium Blend 50ml)",
    nameEn: "Al Basha Special Dokha Warm (Medium Blend 50ml)",
    nameAr: "دوخة الباشا الخاصة دافئة (خلطة متوسطة 50 مل)",
    category: ItemCategory.TOBACCO,
    subCategory: "Warm Blend",
    brand: "AL BASHA",
    countryOfOrigin: "UAE",
    cost: 1.800,
    price: 3.500,
    retailPrice: 3.500,
    semiWholesalePrice: 3.000,
    wholesalePrice: 2.600,
    unit: "bottle",
    stockQuantity: 390,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-016",
    sku: "DK-MDW-WD-GOLD",
    barcode: "6281234500163",
    name: "Handcrafted Ebony Wood Medwakh with Gold Ring",
    nameEn: "Handcrafted Ebony Wood Medwakh with Gold Ring",
    nameAr: "مدواخ خشب أبنوس يدوي الصنع مع حلقة ذهبية",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Wood Medwakh",
    brand: "Bin Essa Classic",
    countryOfOrigin: "Kuwait",
    cost: 3.200,
    price: 6.500,
    retailPrice: 6.500,
    semiWholesalePrice: 5.500,
    wholesalePrice: 4.800,
    unit: "pcs",
    stockQuantity: 205,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-017",
    sku: "TB-GLD-VIR-50G",
    barcode: "6281234500170",
    name: "Golden Virginia Rolling Tobacco Pouch (50g)",
    nameEn: "Golden Virginia Rolling Tobacco Pouch (50g)",
    nameAr: "تبغ لف غولدن فيرجينيا أوريجينال (50 غرام)",
    category: ItemCategory.TOBACCO,
    subCategory: "Virginia Blend",
    brand: "Golden Virginia",
    countryOfOrigin: "UK",
    cost: 2.100,
    price: 3.750,
    retailPrice: 3.750,
    semiWholesalePrice: 3.250,
    wholesalePrice: 2.950,
    unit: "pouch",
    stockQuantity: 355,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-018",
    sku: "PA-BR-PIPE-9MM",
    barcode: "6281234500187",
    name: "Classic Briar Wood Smoking Pipe (9mm Filter)",
    nameEn: "Classic Briar Wood Smoking Pipe (9mm Filter)",
    nameAr: "غليون كلاسيكي خشب براير (فلتر 9 ملم)",
    category: ItemCategory.ACCESSORIES,
    subCategory: "Briar Pipes",
    brand: "Peterson",
    countryOfOrigin: "Ireland",
    cost: 4.200,
    price: 8.500,
    retailPrice: 8.500,
    semiWholesalePrice: 7.000,
    wholesalePrice: 6.200,
    unit: "pcs",
    stockQuantity: 125,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-019",
    sku: "MR-DAI-ROD-CB1",
    barcode: "6281234500194",
    name: "Daiwa Saltist Boat Fishing Rod Combo 7ft",
    nameEn: "Daiwa Saltist Boat Fishing Rod Combo 7ft",
    nameAr: "قصبة صيد دايوا سالتيست للبحر والقوارب 7 قدم",
    category: ItemCategory.OTHER,
    subCategory: "Fishing Rods",
    brand: "Daiwa",
    countryOfOrigin: "Japan",
    cost: 18.000,
    price: 32.500,
    retailPrice: 32.500,
    semiWholesalePrice: 27.000,
    wholesalePrice: 24.000,
    unit: "set",
    stockQuantity: 68,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-020",
    sku: "MR-SHM-REL-400",
    barcode: "6281234500200",
    name: "Shimano Sedona 4000 Spinning Reel",
    nameEn: "Shimano Sedona 4000 Spinning Reel",
    nameAr: "ماكينة صيد شيمانو سيدونا 4000 سبينينغ",
    category: ItemCategory.OTHER,
    subCategory: "Reels",
    brand: "Shimano",
    countryOfOrigin: "Japan",
    cost: 14.500,
    price: 26.000,
    retailPrice: 26.000,
    semiWholesalePrice: 22.000,
    wholesalePrice: 19.500,
    unit: "pcs",
    stockQuantity: 82,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-021",
    sku: "JM-ACR-DESK-SN",
    barcode: "6281234500217",
    name: "Custom Laser Cut Acrylic Executive Desk Sign",
    nameEn: "Custom Laser Cut Acrylic Executive Desk Sign",
    nameAr: "لافتة مكتبية تنفيذية أكريليك مخصصة قص ليزر",
    category: ItemCategory.ART_SUPPLIES,
    subCategory: "Acrylic Signage",
    brand: "JM Art Zone",
    countryOfOrigin: "Kuwait",
    cost: 3.500,
    price: 9.500,
    retailPrice: 9.500,
    semiWholesalePrice: 7.500,
    wholesalePrice: 6.500,
    unit: "pcs",
    stockQuantity: 205,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
  {
    id: "item-022",
    sku: "JM-PRN-MUG-CST",
    barcode: "6281234500224",
    name: "Personalized Ceramic Sublimation Coffee Mug",
    nameEn: "Personalized Ceramic Sublimation Coffee Mug",
    nameAr: "كوب قهوة سيراميك طباعة حرارية مخصصة",
    category: ItemCategory.ART_SUPPLIES,
    subCategory: "Ceramic Mugs",
    brand: "JM Art Zone",
    countryOfOrigin: "Kuwait",
    cost: 0.650,
    price: 2.500,
    retailPrice: 2.500,
    semiWholesalePrice: 1.800,
    wholesalePrice: 1.500,
    unit: "pcs",
    stockQuantity: 540,
    isActive: true,
    allowSale: true,
    allowPurchase: true,
    allowDiscount: true,
    allowGift: true,
    posVisibility: true,
  },
];

async function seedMasterCatalog() {
  console.log('=== Seeding Master Products Catalog (22 SKUs) ===');

  for (const itemData of officialItems) {
    await prisma.item.upsert({
      where: { sku: itemData.sku },
      update: {
        barcode: itemData.barcode,
        name: itemData.name,
        nameEn: itemData.nameEn,
        nameAr: itemData.nameAr,
        category: itemData.category,
        subCategory: itemData.subCategory,
        brand: itemData.brand,
        countryOfOrigin: itemData.countryOfOrigin,
        cost: itemData.cost,
        price: itemData.price,
        retailPrice: itemData.retailPrice,
        semiWholesalePrice: itemData.semiWholesalePrice,
        wholesalePrice: itemData.wholesalePrice,
        unit: itemData.unit,
        stockQuantity: itemData.stockQuantity,
        isActive: itemData.isActive,
        allowSale: itemData.allowSale,
        allowPurchase: itemData.allowPurchase,
        allowDiscount: itemData.allowDiscount,
        allowGift: itemData.allowGift,
        posVisibility: itemData.posVisibility,
      },
      create: {
        id: itemData.id,
        sku: itemData.sku,
        barcode: itemData.barcode,
        name: itemData.name,
        nameEn: itemData.nameEn,
        nameAr: itemData.nameAr,
        category: itemData.category,
        subCategory: itemData.subCategory,
        brand: itemData.brand,
        countryOfOrigin: itemData.countryOfOrigin,
        cost: itemData.cost,
        price: itemData.price,
        retailPrice: itemData.retailPrice,
        semiWholesalePrice: itemData.semiWholesalePrice,
        wholesalePrice: itemData.wholesalePrice,
        unit: itemData.unit,
        stockQuantity: itemData.stockQuantity,
        isActive: itemData.isActive,
        allowSale: itemData.allowSale,
        allowPurchase: itemData.allowPurchase,
        allowDiscount: itemData.allowDiscount,
        allowGift: itemData.allowGift,
        posVisibility: itemData.posVisibility,
      },
    });
  }

  const count = await prisma.item.count();
  console.log(`Successfully seeded ${count} master catalog items in PostgreSQL.`);
}

seedMasterCatalog()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
